config/routes.rb
Rails.application.routes.draw do
	root "pages#home"
	get 'pages/home', to: 'pages#home'

	resources :recipes do
		resources :comments, only: [:create]
	end

	get '/signup', to: 'chefs#new'
	resources :chefs, except: [:new]

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	resources :ingredients, except: [:destroy]
	get '/chat', to: 'chatrooms#show'
	resources :messages, only: [:create]

	mount ActionCable.server => '/cable'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	validates :name, presence: true
	validates :description, presence: true, length: { minimum: 5, maximum: 500 }

	belongs_to :chef
	validates :chef_id, presence: true
	default_scope -> { order(updated_at: :desc) }

	has_many :recipe_ingredients
	has_many :ingredients, through: :recipe_ingredients
	has_many :comments, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :set_recipe, only: [:show, :edit, :update]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@recipes = Recipe.paginate(page: params[:page], per_page: 5)
	end

	def show
		@comment = Comment.new
		@comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.chef = current_chef
		if @recipe.save
			flash[:success] = "Recipe was created successfully"
			redirect_to recipe_path(@recipe)
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		@recipe.chef = Chef.first
		if @recipe.update(recipe_params)
			flash[:success] = "Recipe was updated successfully"
			redirect_to recipe_path(@recipe)
		else
			render 'new'
		end
	end

	def destroy
		Recipe.find(params[:id]).destroy
		redirect_to recipes_path
		flash[:success] = "Recipe was successfully deleted"
	end

	private

		def set_recipe
			@recipe = Recipe.find(params[:id])
		end

		def recipe_params
			params.require(:recipe).permit(:name, :description)
		end

		def require_same_user
			if current_chef != @recipe.chef && !current_chef.admin?
				flash[:danger] = "You do not have permission to perform that action"
				redirect_to recipe_path(@recipe)
			end
		end

end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
	<div class="col-md-12">
		<%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-md-2">
					<%= f.label :name, "Name:" %>
				</div>
				<div class="col-md-8">
					<%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-md-2">
					<%= f.label :description, "Steps:" %>
				</div>
				<div class="col-md-8">
					<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<%= f.submit(@recipe.new_record? ? "Create Recipe" : "Update my Recipe", class: "btn btn-warning btn-primary btn-lg btn-xlarge btn-color") %>
				</div>
			</div>
		<% end %>
		<div class="col-md-5 col-md-offset-4 index-link index-link-padding">
			[ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
		</div>
	</div>
</div>

app/views/recipes/_recipe.html.erb
<ul>
	<% obj.each do |recipe| %>
		<li>
			<div class="col-md-2">
				<div class="chef_info center">
					<%= gravatar_for(recipe.chef, size: 100) %>
				</div>
			</div>
			<div class="col-md-10 index-link well">
				<h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
				<p><%= truncate(recipe.description, length: 150) %></p>
				<p>
					<small><%= pluralize(recipe.comments.count, "comment") if recipe.comments.count != 0 %></small>
				</p>
				<p>
					<% if recipe.ingredients.count != 0 %>
						<span style="text-decoration: underline;">Ingredients:</span>
						<% recipe.ingredients.each do |ing| %>
							<span class="badge"><%= link_to ing.name, ingredient_path(ing) %> &nbsp; </span>
						<% end %>
					<% else %>
						<div style="text-decoration: underline;">No ingredients yet</div>
					<% end %>
				</p>
				<p>
					<span class="quiet"><small><%= time_ago_in_words(recipe.created_at) %>  ago by <%= recipe.chef.chefname %></small></span>
				</p>
				<% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
					<div class="recipe-action">
						<%= link_to "Edit recipe", edit_recipe_path(recipe), class: "btn btn-xs btn-warning btn-color" %>
						<%= link_to "Delete Recipe", recipe_path(recipe), method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: "btn btn-xs btn-danger" %>
					</div>
				<% end %>
			</div>
		</li>
		<br />
	<% end %>
</ul>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit a recipe" %>

<%= render 'form' %>

<p>
	<div class="center">
		<div class="index-link index-link-padding col-md-15 col-md-offset-14">
			<%= link_to "Cancel changes", recipe_path(@recipe) %>		
		</div>
	</div>
</p>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "Listing all Recipes" %>

<div align="center">
	<%= will_paginate @recipes %>
</div>
<%= render 'recipes/recipe', obj: @recipes %>
<div align="center">
	<%= will_paginate @recipes %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="well col-md-8 col-md-offset-2 row">
	<h4 class="center description"><strong>Steps: </strong></h4>
	<hr />
	<%= simple_format(@recipe.description) %>
	<hr />
	<div class="pull-right">
		<p class="center">
			<em>Created by:</em>
		</p>
		<p class="center">
			<%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
		</p>
		<p class="center">
			<small><%= @recipe.chef.chefname.capitalize %></small>
		</p>
		<p>
			<div class="pull-right">created: <%= time_ago_in_words(@recipe.created_at) %> ago</div>
		</p>
	</div>
	<p>
		<div class="recipe-action">
			<div class="index-link index-link-padding col-md-15 col-md-offset-14">
				<% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
					<%= link_to "Edit recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning btn-color" %>
					<%= link_to "Delete Recipe", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: "btn btn-xs btn-danger" %>
				<% end %>
				<%= link_to "Return to recipes listing", recipes_path, class: "btn btn-xs btn-primary" %>
			</div>
		</div>
	</p>
</div>

<% if logged_in? %>
	<div class="">
		<div class="col-md-8 col-md-offset-1">
			<h3> Comments: </h3>
			<hr />
			<%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
				<div class="form-group">
					<div class="control-label col-md-2">
						<%= f.label :description, "Comment:" %>
					</div>
					<div class="col-md-8">
						<%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter Comment Here" %>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-offset-2 col-md-10">
						<%= f.submit "Submit Comment", class: "btn btn-warning btn-primary btn-lg btn-xlarge btn-color" %>
					</div>
				</div>
			<% end %>
			<hr />
		</div>
	</div>
<% end %>

<% if @recipe.comments.count != 0 %>
	<div class="">
		<div class="col-md-8 col-md-offset-2">
			<h3>Prior comments:</h3>
			<div id="messages">
				<%= render partial: 'comments/comments', object: @comments %>
			</div>
		</div>
	</div>
<% else %>
	<div class="">
		<div class="col-md-8 col-md-offset-2">
			<h3>No comments yet!</h3>
		</div>
	</div>s
<% end %>